### ISSUE TITLE
Geolocation Processor empty geo fields

### ISSUE THREAD

**Issue by davama** [Graylog2/graylog-plugin-map-widget#37]
Hello,

Trying to set this up. Follow the [doc](http://docs.graylog.org/en/2.2/pages/geolocation.html) to the letter. I was able to get the geo fields, `<field>_geolocation`, when i ran the command:

`nc -w1 <graylog_host> 5555 <<< '8.8.8.8'`

Unfortunately it does not work with normal logs that come in. On my input i have an extractor that copies the IP from the message into gl2_remote_ip field, which works.

```
Trying to extract data from message into gl2_remote_ip, leaving the original intact.
Condition
     Will only attempt to run if the message matches the regular expression from ([0-9]+.[0-9]+.[0-9]+.[0-9]+|\S+)(\s|:\s)
Configuration 
     regex_value: from ([0-9]+.[0-9]+.[0-9]+.[0-9]+|\S+)(\s|:\s)
```

Also set `GeoIP Resolver	` to last (3) in "Message Processors Configuration".
```
#	Processor	Status
1	Pipeline Processor	active
2	Message Filter Chain	active
3	GeoIP Resolver	active
```
This is how the Plugin is configured:
```
Enabled: yes
Database type: City database
Database path: /etc/graylog/server/GeoLite2-City.mmdb
```
The DB exists and has the correct permissions:
```
ll /etc/graylog/server/GeoLite2-City.mmdb
-rw-r--r-- 1 root root 53531421 Mar 29 19:46 /etc/graylog/server/GeoLite2-City.mmdb
```

Not really to sure what is going on. Any input is appreciated.
Hope this makes sense.

CentOS Linux release 7.3.1611 (Core) 
Graylog 2.2.2+691b4b7

Thanks
dave

**Comment by jalogisch** [comment]
@davama this will not work with ips that are mentioned in [rfc 1918](https://tools.ietf.org/html/rfc1918)

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
@davama What's the actual content of the `gl2_source_ip` field when your extractor ran?

The regular expression looks a bit fishy to me and could match any non-whitespace characters in the first capturing group.

**Comment by davama** [comment]
@joschi thanks for replying. please see forum

i moved issue to discussion forum here https://community.graylog.org/t/geolocation-processor-empty-geo-fields/639
