### ISSUE TITLE
Add DNS LOC records support

### ISSUE THREAD

**Issue by davama** [Graylog2/graylog-plugin-map-widget#38]
would this be possible?
https://en.wikipedia.org/wiki/LOC_record

Where graylog looks at DNS record then the mmdb file or vice versa.

thanks
Dave

**Comment by davama** [comment]
wait a min. thinking about this a bit...
LOC records are for hostnames so... not sure if this would be feasible

**Comment by jalogisch** [comment]
with some future pipeline rules the lookup to dns will be possible.

will close this and please watch https://github.com/Graylog2/graylog2-server/issues/3691 to get updates on this.

**Comment by davama** [comment]
Thanks!
