### ISSUE TITLE
Ubiquiti not send source ip of device

### ISSUE THREAD

**Issue by giorgiolago** [Graylog2/graylog-plugin-map-widget#63]
Hello, I am using the latest version of graylog 2.4, I have detected that ubiquiti devices in the source field instead of sending the ip of the device it sends random fields like service name (lighttpd, drogbear) or the username of the logged in user at the moment but never the ip of the device, how can I solve this?

![image](https://user-images.githubusercontent.com/35151682/34629591-78568d26-f247-11e7-913f-e6d69423f7eb.png)
![image](https://user-images.githubusercontent.com/35151682/34629877-89fc23f0-f248-11e7-83b8-bbaafd3ddd77.png)
![image](https://user-images.githubusercontent.com/35151682/34629910-aa6a5fe4-f248-11e7-8c25-ebdc64df72f6.png)

I try this:
rule "Set Source IP" when has_field("source") then set_field("source_ip", to_string($message.gl2_remote_ip)); end

But not happening :-(

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jalogisch** [comment]
@giorgiolago just to give you some backround information.

I did personal use Unifi 5.6.26 with some APs, Switches and Routers on the latest Firmware and this is working without any issues.

You should stop and re-enable the Syslog function and check that. But as already writte. Please in the IRC or Discussion forum.

**Comment by giorgiolago** [comment]
i'm using AF5X and POWERBEAM M5 , i try re-enable syslog but doenst work
