### ISSUE TITLE
*_geolocation using type:"geo_point"

### ISSUE THREAD

**Issue by shanipribadi** [Graylog2/graylog-plugin-map-widget#7]
Hello,
I was trying out graylog2 map widget and trying to compare it with kibana map visualization. I tried to visualize the *_geolocation fields in kibana but apparently the type mapping is string, so it cannot be visualized in kibana. So I added 

```
{
            "geolocation": {
              "mapping": {
                "type": "geo_point"
              },
              "match": "*_geolocation"
            }
},
```

to _template/graylog-internal mapping.
After that all graylong geoip resolver fields are mapped as geo_point and can be visualized in kibana.

But this apparently makes it impossible to visualize the same field in graylog map widget, returning 

> Could not load map information
> Loading map information failed: cannot POST http://127.0.0.1:12900/plugins/org.graylog.plugins.map/mapdata (500)

What is the preferred way to do this?

Thank you

**Comment by kroepke** [comment]
Graylog currently doesn't support the geo_point mapping type, correct.
If you want to use both, you could use a copy_to mapping parameter in a custom index template to create a second field for use with kibana:
https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html

**Comment by Nyanyah** [comment]
I am interested in visualizing the geolocation fields in kibana only. May I ask where you added that part in the template please ?
Also, doesn't the graylog internal template overrides your change after you create a new index ?

**Comment by matthgyver** [comment]
I've read documentation about custom index mapping but I can't add custom mapping to "convert" string field as geo_point.
What is the JSON qury to do that please ?

**Comment by joschi** [comment]
@matthgyver That's not possible. See @kroepke's comment for a link to the Elasticsearch documentation and the `copy_to` mapping type.

**Comment by matthgyver** [comment]
@joschi I'll take a look. I've think that it was possible because shanipribadi say that he have do that in the first message of this issue

**Comment by matthgyver** [comment]
I'm triyng `copy_to` but I think that I'm too noob sorry ...
Is it possible to copy all data from field name are "*_geolocation" to a unique field ?
Have you an example of json query to do that as custom mapping please ?

**Comment by joschi** [comment]
@matthgyver We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by matthgyver** [comment]
@joschi OK sorry.

**Comment by jalogisch** [comment]
as this is dup of https://github.com/Graylog2/graylog2-server/issues/2113 this will be closed
